/**
 * features.js - AlgivixAI Advanced Features
 * ==========================================
 * Developer: EMEMZYVISUALS DIGITALS
 *
 * Features:
 * - AI Memory & weekly summary
 * - Weekly performance report
 * - Smart task assignment
 * - Deadline chaser
 * - Developer trivia game
 * - Good morning posts
 * - Roast mode 😂
 * - Meeting notes
 * - MVP of the week
 * - Auto code review
 * - Mood check
 * - Secret admin commands
 */

const { askGroq } = require("./ai");

// ─── Formatting Helpers ───────────────────────────────────────────────────────
const fmt      = t => `*${t}*`;
const italic   = t => `_${t}_`;
const divider  = () => `━━━━━━━━━━━━━━━━━━━━`;
const tagPhone = p => `@${(p || "").split("@")[0].split(":")[0]}`;

// ─── AI Memory ────────────────────────────────────────────────────────────────
const memory = {
  messages:     [],   // { phone, text, time }
  discussions:  [],   // Key topics detected
  taskAssigns:  [],   // { task, assignee, deadline, assignedBy }
  moodHistory:  [],   // { phone, mood, time }
  triviaScores: new Map(), // { phone: score }
  mvpVotes:     new Map(), // { phone: activityCount }
  warnings:     new Map(), // { phone: count }
  meetingActive: false,
  meetingNotes:  [],
  ghostMode:     false,
  hypeMode:      false,
  lockdown:      false,
};

function recordMessage(phone, text) {
  memory.messages.push({ phone, text, time: Date.now() });
  // Keep last 500 messages only
  if (memory.messages.length > 500) memory.messages.shift();

  // Track activity for MVP
  const current = memory.mvpVotes.get(phone) || 0;
  memory.mvpVotes.set(phone, current + 1);
}

// ─── Weekly Summary ───────────────────────────────────────────────────────────
async function generateWeeklySummary() {
  try {
    const recent = memory.messages.slice(-100).map(m => `${m.phone}: ${m.text}`).join("\n");
    if (!recent) return `📋 ${fmt("Weekly Summary")}\n${divider()}\nNot enough activity this week yet!`;

    const summary = await askGroq(
      `Summarize these WhatsApp group conversations in 5 bullet points. Focus on main topics, decisions made, and key discussions:\n\n${recent}`,
      "general"
    );

    return (
      `🧠 ${fmt("Weekly Discussion Summary")}\n${divider()}\n` +
      `${summary}\n\n` +
      `📊 ${fmt("Stats:")}\n` +
      `💬 Total messages: ${memory.messages.length}\n` +
      `👥 Active members: ${new Set(memory.messages.map(m => m.phone)).size}\n` +
      `📅 Generated: ${new Date().toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })}`
    );
  } catch (e) {
    return `❌ Could not generate summary: ${e.message}`;
  }
}

// ─── Weekly Performance Report ────────────────────────────────────────────────
function generatePerformanceReport() {
  const activityMap = memory.mvpVotes;
  if (activityMap.size === 0) {
    return `📊 ${fmt("Weekly Performance Report")}\n${divider()}\nNo activity recorded yet this week!`;
  }

  // Sort by activity
  const sorted  = [...activityMap.entries()].sort((a, b) => b[1] - a[1]);
  const mvp     = sorted[0];
  const quiet   = sorted.filter(([, count]) => count < 3);
  const total   = [...activityMap.values()].reduce((a, b) => a + b, 0);

  let report = `📊 ${fmt("Weekly Performance Report")}\n${divider()}\n`;
  report    += `🏆 ${fmt("Most Active:")} ${tagPhone(mvp[0])} (${mvp[1]} messages)\n`;
  report    += `💬 ${fmt("Total Messages:")} ${total}\n`;
  report    += `👥 ${fmt("Active Members:")} ${activityMap.size}\n\n`;

  report += `📈 ${fmt("Activity Breakdown:")}\n`;
  sorted.slice(0, 5).forEach(([phone, count], i) => {
    const bar = "█".repeat(Math.min(count, 10));
    report   += `${i + 1}. ${tagPhone(phone)} ${bar} (${count})\n`;
  });

  if (quiet.length > 0) {
    report += `\n👀 ${fmt("Quiet Members:")}\n`;
    quiet.forEach(([phone]) => { report += `• ${tagPhone(phone)}\n`; });
  }

  report += `\n_Report generated by AlgivixAI_ 🤖`;
  return report;
}

// ─── MVP of the Week ──────────────────────────────────────────────────────────
function getMVP() {
  if (memory.mvpVotes.size === 0) return null;
  const sorted = [...memory.mvpVotes.entries()].sort((a, b) => b[1] - a[1]);
  return sorted[0];
}

function generateMVPAnnouncement() {
  const mvp = getMVP();
  if (!mvp) return `🏆 ${fmt("MVP of the Week")}\n${divider()}\nNot enough data yet — keep engaging! 💪`;

  return (
    `🏆 ${fmt("MVP OF THE WEEK!")}\n${divider()}\n` +
    `🌟 Congratulations to ${tagPhone(mvp[0])}!\n\n` +
    `They've been the most active and engaged member this week with ${fmt(mvp[1] + " messages")}!\n\n` +
    `Keep up the amazing work! You're making the Algivix Dev Team proud! 💪🔥\n\n` +
    `${italic("Keep contributing and you could be next week's MVP!")} 👑`
  );
}

// ─── Trivia Game ──────────────────────────────────────────────────────────────
let triviaActive    = false;
let triviaQuestion  = null;
let triviaAnswer    = null;
let triviaTimer     = null;

const TRIVIA_QUESTIONS = [
  { q: "What does *API* stand for?", a: "application programming interface" },
  { q: "What does *CSS* stand for?", a: "cascading style sheets" },
  { q: "What does *HTML* stand for?", a: "hypertext markup language" },
  { q: "What does *SQL* stand for?", a: "structured query language" },
  { q: "What does *HTTP* stand for?", a: "hypertext transfer protocol" },
  { q: "What does *JSON* stand for?", a: "javascript object notation" },
  { q: "Which language runs in the browser natively?", a: "javascript" },
  { q: "What symbol is used for comments in Python?", a: "#" },
  { q: "What does *RAM* stand for?", a: "random access memory" },
  { q: "What does *CPU* stand for?", a: "central processing unit" },
  { q: "What does *OOP* stand for?", a: "object oriented programming" },
  { q: "What does *IDE* stand for?", a: "integrated development environment" },
  { q: "What does *Git* stand for?", a: "global information tracker" },
  { q: "What language is used for Android development?", a: "kotlin" },
  { q: "What does *UI* stand for?", a: "user interface" },
];

function startTrivia(sendFn, groupJid) {
  if (triviaActive) return `⚠️ A trivia question is already active! Answer it first!`;

  const q        = TRIVIA_QUESTIONS[Math.floor(Math.random() * TRIVIA_QUESTIONS.length)];
  triviaQuestion = q.q;
  triviaAnswer   = q.a.toLowerCase();
  triviaActive   = true;

  // Auto-close after 2 minutes
  triviaTimer = setTimeout(async () => {
    if (triviaActive) {
      triviaActive = false;
      await sendFn(groupJid,
        `⏰ ${fmt("Time's up!")}\nThe answer was: ${fmt(triviaAnswer.toUpperCase())}\nBetter luck next time! 😄`
      );
    }
  }, 2 * 60 * 1000);

  return (
    `🎮 ${fmt("DEV TRIVIA TIME!")}\n${divider()}\n` +
    `❓ ${triviaQuestion}\n\n` +
    `⏰ You have ${fmt("2 minutes")} to answer!\n` +
    `🏆 First correct answer wins a point!\n\n` +
    `${italic("Type your answer now...")}`
  );
}

function checkTriviaAnswer(phone, text, sendFn, groupJid) {
  if (!triviaActive) return null;
  const answer = text.toLowerCase().trim();
  if (answer.includes(triviaAnswer)) {
    triviaActive = false;
    if (triviaTimer) clearTimeout(triviaTimer);

    // Add point
    const current = memory.triviaScores.get(phone) || 0;
    memory.triviaScores.set(phone, current + 1);

    return (
      `🎉 ${fmt("CORRECT!!")} ${tagPhone(phone)} got it!\n${divider()}\n` +
      `✅ Answer: ${fmt(triviaAnswer.toUpperCase())}\n` +
      `🏆 ${tagPhone(phone)}'s score: ${fmt(current + 1 + " points")}\n\n` +
      `${italic("Great job! 🔥")}`
    );
  }
  return null;
}

function getTriviaLeaderboard() {
  if (memory.triviaScores.size === 0) {
    return `🏆 ${fmt("Trivia Leaderboard")}\n${divider()}\nNo scores yet! Start with: ${fmt("!trivia")}`;
  }
  const sorted = [...memory.triviaScores.entries()].sort((a, b) => b[1] - a[1]);
  let board    = `🏆 ${fmt("Trivia Leaderboard")}\n${divider()}\n`;
  const medals = ["🥇", "🥈", "🥉"];
  sorted.forEach(([phone, score], i) => {
    board += `${medals[i] || `${i + 1}.`} ${tagPhone(phone)} — ${fmt(score + " pts")}\n`;
  });
  return board;
}

// ─── Good Morning Post ────────────────────────────────────────────────────────
const DEV_QUOTES = [
  `"Any fool can write code that a computer can understand. Good programmers write code that humans can understand." — Martin Fowler`,
  `"First, solve the problem. Then, write the code." — John Johnson`,
  `"Code is like humor. When you have to explain it, it's bad." — Cory House`,
  `"Make it work, make it right, make it fast." — Kent Beck`,
  `"The best error message is the one that never shows up." — Thomas Fuchs`,
  `"Simplicity is the soul of efficiency." — Austin Freeman`,
  `"Programs must be written for people to read, and only incidentally for machines to execute." — Harold Abelson`,
  `"The most disastrous thing that you can ever learn is your first programming language." — Alan Kay`,
];

function getGoodMorning() {
  const quote   = DEV_QUOTES[Math.floor(Math.random() * DEV_QUOTES.length)];
  const days    = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const day     = days[new Date().getDay()];
  const greets  = ["Rise and code!", "Let's build something amazing today!", "Another day, another commit!", "Time to ship some features!"];
  const greet   = greets[Math.floor(Math.random() * greets.length)];

  return (
    `🌅 ${fmt("Good Morning, Algivix Dev Team!")}\n${divider()}\n` +
    `Happy ${fmt(day)}! ${greet} 💪\n\n` +
    `💡 ${fmt("Dev Quote of the Day:")}\n${italic(quote)}\n\n` +
    `📌 Check your tasks: ${fmt("!task")}\n` +
    `🤖 Need help? Use: ${fmt("!ai <question>")}\n\n` +
    `${italic("Let's make today count! 🚀")}`
  );
}

// ─── Roast Mode 😂 ────────────────────────────────────────────────────────────
async function generateRoast(targetPhone, reason) {
  try {
    const prompt = `Generate a funny, lighthearted, professional roast for a developer named ${targetPhone} ${reason ? "because: " + reason : "just for fun"}. Keep it funny but not offensive. Max 3 sentences. Make it dev/coding themed.`;
    const roast  = await askGroq(prompt, "general");
    return (
      `😂 ${fmt("ROAST MODE ACTIVATED!")}\n${divider()}\n` +
      `🎯 Target: ${tagPhone(targetPhone)}\n\n` +
      `${roast}\n\n` +
      `${italic("All in good fun! 😄🔥")}`
    );
  } catch {
    const fallbacks = [
      `😂 ${tagPhone(targetPhone)}'s code is so bad, even Stack Overflow gave up! 💀`,
      `🤣 ${tagPhone(targetPhone)} writes commits like "fixed stuff" and calls it documentation! 😭`,
      `😂 ${tagPhone(targetPhone)}'s debugging method: add console.log everywhere and pray! 🙏`,
    ];
    return `${fmt("ROAST!")}\n${divider()}\n${fallbacks[Math.floor(Math.random() * fallbacks.length)]}\n\n${italic("All love! 😄")}`;
  }
}

// ─── Meeting Notes ────────────────────────────────────────────────────────────
function startMeeting() {
  memory.meetingActive = true;
  memory.meetingNotes  = [];
  return (
    `📝 ${fmt("MEETING STARTED!")}\n${divider()}\n` +
    `I'm now recording all messages as meeting notes.\n\n` +
    `💡 Share your points and I'll capture them.\n` +
    `When done, say: ${fmt("end meeting")}\n\n` +
    `${italic("Meeting in progress... 🎙️")}`
  );
}

async function endMeeting() {
  if (!memory.meetingActive) return `⚠️ No meeting is currently active. Say ${fmt("start meeting")} to begin.`;
  memory.meetingActive = false;

  if (memory.meetingNotes.length === 0) {
    return `📝 ${fmt("Meeting Ended")}\nNo notes were recorded.`;
  }

  const notesText = memory.meetingNotes.map((n, i) => `${i + 1}. ${n.phone}: ${n.text}`).join("\n");

  try {
    const summary = await askGroq(
      `Summarize these meeting notes into a clean, professional meeting summary with key decisions and action items:\n\n${notesText}`,
      "general"
    );
    return (
      `📋 ${fmt("MEETING SUMMARY")}\n${divider()}\n` +
      `📅 ${new Date().toLocaleString("en-US", { timeZone: "Africa/Lagos", dateStyle: "medium", timeStyle: "short" })}\n` +
      `👥 Participants: ${new Set(memory.meetingNotes.map(n => n.phone)).size}\n` +
      `💬 Total points: ${memory.meetingNotes.length}\n\n` +
      `${summary}\n\n` +
      `${italic("Summary generated by AlgivixAI 🤖")}`
    );
  } catch {
    let summary = `📋 ${fmt("MEETING NOTES")}\n${divider()}\n`;
    memory.meetingNotes.forEach((n, i) => { summary += `${i + 1}. ${tagPhone(n.phone)}: ${n.text}\n`; });
    return summary;
  }
}

// ─── Mood Check ───────────────────────────────────────────────────────────────
function startMoodCheck(sendFn, groupJid) {
  return (
    `💭 ${fmt("MOOD CHECK!")}\n${divider()}\n` +
    `How's everyone feeling today?\n\n` +
    `Reply with:\n` +
    `😊 ${fmt("1")} or "great" — Feeling good!\n` +
    `😐 ${fmt("2")} or "okay" — Doing alright\n` +
    `😔 ${fmt("3")} or "bad" — Need support\n\n` +
    `${italic("Your response helps us support each other! 💙")}`
  );
}

function recordMood(phone, text) {
  const lower = text.toLowerCase();
  let mood    = null;
  if (lower.includes("1") || lower.includes("great") || lower.includes("good") || lower.includes("amazing")) mood = "😊 great";
  else if (lower.includes("2") || lower.includes("okay") || lower.includes("fine")) mood = "😐 okay";
  else if (lower.includes("3") || lower.includes("bad") || lower.includes("sad") || lower.includes("stressed")) mood = "😔 struggling";
  if (mood) {
    memory.moodHistory.push({ phone, mood, time: Date.now() });
    return mood;
  }
  return null;
}

function getMoodSummary() {
  if (memory.moodHistory.length === 0) return `💭 No mood data yet. Use ${fmt("!mood")} to check in!`;
  const counts = { great: 0, okay: 0, struggling: 0 };
  memory.moodHistory.forEach(m => {
    if (m.mood.includes("great")) counts.great++;
    else if (m.mood.includes("okay")) counts.okay++;
    else counts.struggling++;
  });
  const total = memory.moodHistory.length;
  return (
    `💭 ${fmt("Team Mood Summary")}\n${divider()}\n` +
    `😊 Great: ${counts.great} (${Math.round(counts.great/total*100)}%)\n` +
    `😐 Okay: ${counts.okay} (${Math.round(counts.okay/total*100)}%)\n` +
    `😔 Struggling: ${counts.struggling} (${Math.round(counts.struggling/total*100)}%)\n\n` +
    `${counts.struggling > 0 ? `💙 ${fmt("Some members need support — check on them!")}` : `🔥 ${fmt("Team morale is strong!")}`}`
  );
}

// ─── Secret Admin Commands ────────────────────────────────────────────────────
function handleSecretCommand(text, phone) {
  const lower = text.toLowerCase().trim();

  if (lower === "nuke warnings") {
    memory.warnings.clear();
    return `💥 ${fmt("DONE!")} All warnings have been cleared! Everyone gets a fresh start. 🔄`;
  }

  if (lower === "ghost mode") {
    memory.ghostMode = !memory.ghostMode;
    return memory.ghostMode
      ? `👻 ${fmt("Ghost Mode ON")} — I'll go silent for 1 hour. Watching but not responding...`
      : `👋 ${fmt("Ghost Mode OFF")} — I'm back! Miss me? 😄`;
  }

  if (lower === "hype mode") {
    memory.hypeMode = !memory.hypeMode;
    return memory.hypeMode
      ? `🔥🔥🔥 ${fmt("HYPE MODE ACTIVATED!!!")} LET'S GOOOOO ALGIVIX DEV TEAM!!! 🚀💪🎉`
      : `😌 ${fmt("Hype Mode OFF")} — Back to professional mode.`;
  }

  if (lower === "lockdown") {
    memory.lockdown = !memory.lockdown;
    return memory.lockdown
      ? `🔐 ${fmt("LOCKDOWN MODE")} — Only admins can interact with me now.`
      : `🔓 ${fmt("Lockdown lifted")} — Everyone can interact again!`;
  }

  if (lower === "reset mvp") {
    memory.mvpVotes.clear();
    return `🔄 ${fmt("MVP scores reset!")} Starting fresh this week!`;
  }

  if (lower === "reset trivia") {
    memory.triviaScores.clear();
    return `🔄 ${fmt("Trivia scores reset!")} New competition begins!`;
  }

  if (lower === "bot stats") {
    return (
      `🤖 ${fmt("AlgivixAI Stats")}\n${divider()}\n` +
      `💬 Messages recorded: ${memory.messages.length}\n` +
      `👥 Unique members tracked: ${memory.mvpVotes.size}\n` +
      `🎮 Trivia players: ${memory.triviaScores.size}\n` +
      `💭 Mood entries: ${memory.moodHistory.length}\n` +
      `📝 Meeting notes: ${memory.meetingNotes.length}\n` +
      `👻 Ghost mode: ${memory.ghostMode ? "ON" : "OFF"}\n` +
      `🔥 Hype mode: ${memory.hypeMode ? "ON" : "OFF"}\n` +
      `🔐 Lockdown: ${memory.lockdown ? "ON" : "OFF"}`
    );
  }

  return null;
}

// ─── Hype Responses ───────────────────────────────────────────────────────────
const HYPE_PREFIXES = [
  "YOOOO!! 🔥🔥🔥 ",
  "LESSGOOOO!! 🚀🚀 ",
  "ALGIVIX DEV TEAM ON FIRE!! 💪🔥 ",
  "WE MOVE!! 🏆🏆 ",
];

function addHype(text) {
  if (!memory.hypeMode) return text;
  const prefix = HYPE_PREFIXES[Math.floor(Math.random() * HYPE_PREFIXES.length)];
  return prefix + text + " 🔥🔥🔥";
}

// ─── Auto Code Review ─────────────────────────────────────────────────────────
function looksLikeCode(text) {
  return [
    /```[\s\S]*```/,
    /function\s+\w+\s*\(/,
    /const\s+\w+\s*=/,
    /import\s+\S+\s+from/,
    /def\s+\w+\s*\(/,
    /class\s+\w+[\s:{]/,
    /SELECT\s+\S+\s+FROM/i,
    /console\.log\s*\(/,
    /=>\s*{/,
    /public\s+(static\s+)?void/,
    /<\/?[a-z][\w]*[\s/>]/i,
  ].some(p => p.test(text));
}

async function autoReviewCode(text) {
  try {
    const review = await askGroq(text, "code_review");
    return (
      `🔍 ${fmt("Auto Code Review by AlgivixAI")}\n${divider()}\n` +
      `${review}\n\n` +
      `${italic("Tip: Use !review <code> for manual review anytime!")}`
    );
  } catch {
    return null;
  }
}

module.exports = {
  memory,
  recordMessage,
  generateWeeklySummary,
  generatePerformanceReport,
  getMVP,
  generateMVPAnnouncement,
  startTrivia,
  checkTriviaAnswer,
  getTriviaLeaderboard,
  getGoodMorning,
  generateRoast,
  startMeeting,
  endMeeting,
  startMoodCheck,
  recordMood,
  getMoodSummary,
  handleSecretCommand,
  addHype,
  looksLikeCode,
  autoReviewCode,
  fmt,
  italic,
  divider,
  tagPhone,
};
